version: '2'

services:

  mongo-proc:
    image: mongo:latest
    restart: always
    user: mongodb
    hostname: mongo-proc
    ports:
        - 27017
    volumes:
        - /etc/localtime:/etc/localtime:ro

  mongo-logs:
    image: mongo:latest
    restart: always
    user: mongodb
    hostname: mongo-logs
    ports:
        - 27017
    volumes:
        - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:alpine
    user: redis
    restart: always
    hostname: opac-proc-redis
    ports:
        - "6379:6379"  # deve ser o mesmo que a env var: OPAC_PROC_REDIS_PORT
    volumes:
      - redis-data-dev:/data
      - /etc/localtime:/etc/localtime:ro

  rq-worker:
    images: scieloorg/opac_proc
    command: /start_worker.sh
    user: nobody
    restart: always
    hostname: opac-proc-rqworker
    links:
      - mongo-proc:mongo-proc
      - mongo-logs:mongo-logs
      - redis:redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scielosp_org:/data:ro
    environment:
      - OPAC_PROC_LOG_LEVEL=DEBUG
      - OPAC_PROC_ARTICLE_META_THRIFT_DOMAIN=articlemeta.scielo.org
      - OPAC_PROC_ARTICLE_META_THRIFT_PORT=11621
      - OPAC_PROC_COLLECTION=spa
      - OPAC_PROC_DEBUG=True
      - OPAC_PROC_TESTING=False
      - OPAC_PROC_SECRET_KEY="s3cr3t-k3y"
      # - OPAC_PROC_SENTRY_DSN=
      # mongo processamento
      - OPAC_PROC_MONGODB_NAME=opac_proc
      - OPAC_PROC_MONGODB_HOST=mongo-proc
      - OPAC_PROC_MONGODB_PORT=27017
      # - OPAC_PROC_MONGODB_USER=
      # - OPAC_PROC_MONGODB_PASS=
      # mongo db do opac
      - OPAC_MONGODB_NAME=${OPAC_MONGODB_NAME}  # nome do banco mongo do OPAC
      - OPAC_MONGODB_HOST=${OPAC_MONGODB_HOST}  # host do banco mongo do OPAC
      - OPAC_MONGODB_PORT=${OPAC_MONGODB_PORT}  # porta do banco mongo do OPAC
      # - OPAC_MONGODB_USER=
      # - OPAC_MONGODB_PASS=
      # mongo logs do opac
      - OPAC_PROC_LOG_MONGODB_NAME=opac_proc_logs
      - OPAC_PROC_LOG_MONGODB_HOST=mongo-logs
      - OPAC_PROC_LOG_MONGODB_PORT=27017
      # - OPAC_PROC_LOG_MONGODB_USER=
      # - OPAC_PROC_LOG_MONGODB_PASS=
      # Redis:
      - OPAC_PROC_REDIS_HOST=redis
      - OPAC_PROC_REDIS_PORT=6379
      
  webapp:
    images: scieloorg/opac_proc
    user: nobody
    restart: always
    hostname: opac-proc-webapp
    links:
      - mongo-proc:mongo-proc
      - mongo-logs:mongo-logs
      - redis:redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scielosp_org:/data:ro
    ports:
      - "9000:8000"
    environment:
      - OPAC_PROC_LOG_LEVEL=DEBUG
      - OPAC_PROC_ARTICLE_META_THRIFT_DOMAIN=articlemeta.scielo.org
      - OPAC_PROC_ARTICLE_META_THRIFT_PORT=11621
      - OPAC_PROC_COLLECTION=spa
      - OPAC_PROC_DEBUG=True
      - OPAC_PROC_TESTING=False
      - OPAC_PROC_SECRET_KEY="s3cr3t-k3y"
      # - OPAC_PROC_SENTRY_DSN=
      # mongo processamento
      - OPAC_PROC_MONGODB_NAME=opac_proc
      - OPAC_PROC_MONGODB_HOST=mongo-proc
      - OPAC_PROC_MONGODB_PORT=27017
      # - OPAC_PROC_MONGODB_USER=
      # - OPAC_PROC_MONGODB_PASS=
      # mongo db do opac
      - OPAC_MONGODB_NAME=${OPAC_MONGODB_NAME}  # nome do banco mongo do OPAC
      - OPAC_MONGODB_HOST=${OPAC_MONGODB_HOST}  # host do banco mongo do OPAC
      - OPAC_MONGODB_PORT=${OPAC_MONGODB_PORT}  # porta do banco mongo do OPAC
      # - OPAC_MONGODB_USER=
      # - OPAC_MONGODB_PASS=
      # mongo logs do opac
      - OPAC_PROC_LOG_MONGODB_NAME=opac_proc_logs
      - OPAC_PROC_LOG_MONGODB_HOST=mongo-logs
      - OPAC_PROC_LOG_MONGODB_PORT=27017
      # - OPAC_PROC_LOG_MONGODB_USER=
      # - OPAC_PROC_LOG_MONGODB_PASS=
      # Redis:
      - OPAC_PROC_REDIS_HOST=redis
      - OPAC_PROC_REDIS_PORT=6379

